### PR TITLE
change createArticle method

### PR DESCRIPTION
**Pull request by iryabov**
add testNewMethod method

### CODE REVIEW

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
[517 methods (517 new, 0 modified)]()   

**Risks**
[129/517 methods not tested]()
[53% coverage]()

**Recommended tests**
[2838 tests]()

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3Ade92cf4b5ef411b7eb05c6847196bf838060998c&baseline_build=realworld%3Aspring-webflux%3A424d433067822bb4fa49bed65e708321f3d807bb)

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
[517 methods (517 new, 0 modified)]()   

**Risks**
[129/517 methods not tested]()
[53% coverage]()

**Recommended tests**
[4188 tests]()

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3Ab500481ae215569f83440cb3f90f7e7b5e76eb8b&baseline_build=realworld%3Aspring-webflux%3A7ec46946fa205eb6b2f0ab177e6b3ae59858a715)

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
2 methods (1 new, 1 modified)   

**Risks**
1/2 methods not tested
86% coverage

**Recommended tests**
21 tests

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
2 methods (1 new, 1 modified)   

**Risks**
All changes tested
100% coverage

**Recommended tests**
None

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
2 methods (0 new, 2 modified)   

**Risks**
All changes tested
100% coverage

**Recommended tests**
None

**Comment by iryabov** [comment]
### Drill4J Bot - Change Testing Report
Comparing the changes made to `realworld/spring-webflux` in the [6af31bd](/Drill4J/realworld-spring-webflux/commit/6af31bd8696ec732724052db082cc9e5473a0f58) with the [33c48ae](/Drill4J/realworld-spring-webflux/commit/33c48aec04d33d1116827822d2b1049021dfaaf4).


Comparison of  `realworld/spring-webflux` changes made in [6af31bd](/Drill4J/realworld-spring-webflux/commit/6af31bd8696ec732724052db082cc9e5473a0f58) versus [33c48ae](/Drill4J/realworld-spring-webflux/commit/33c48aec04d33d1116827822d2b1049021dfaaf4).

**Changes**
2 methods (1 new, 1 modified)   

**Risks**
1/2 methods not tested
86% coverage

**Recommended tests**
21 tests

**Pull request closed without merging**
