### PR TITLE
Test 1

### PR DESCRIPTION
**Pull request by iryabov**

### CODE REVIEW

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report            
Changes
[0 methods (0 new, 0 modified)]()

Risks
[0/0 methods not tested]()
[0.0% coverage]()

Recommended tests
[0 tests]()            

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A76e521f8fb85f6542c8fe3daa1cda13fe27b138a&baseline_build=realworld%3Aspring-webflux%3Acce415b8bf30af9b3d96f0283097ff7f066e7a4d)

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report            
Changes
[0 methods (0 new, 0 modified)]()

Risks
[0/0 methods not tested]()
[0.0% coverage]()

Recommended tests
[0 tests]()            

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3Ab1541bbf48453a420bddcb2b09fa7cc13f15b9c9&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report            
Changes
[0 methods (0 new, 0 modified)]()

Risks
[0/0 methods not tested]()
[0.0% coverage]()

Recommended tests
[0 tests]()            

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A301d4953f8384f35a5694f30055c1b0fd9c9c5db&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Comment by RomanDavlyatshin** [comment]
### Drill4J Bot - Change Testing Report            
Changes
[1 methods (0 new, 0 modified)]()

Risks
[0/1 methods not tested]()
[1.0% coverage]()

Recommended tests
[0 tests]()            

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A7f92dcb6f24a9967793b11f11b8795bd2a2d93e4&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Comment by iryabov** [comment]
### Drill4J Bot - Change Testing Report            
Changes
[3 methods (1 new, 2 modified)]()

Risks
[All changes tested]()
[85% coverage]()

Recommended tests
None        

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A301d4953f8384f35a5694f30055c1b0fd9c9c5db&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Comment by iryabov** [comment]
### Drill4J Bot - Change Testing Report            
**Changes**
No changes detected

**Risks**
All changes tested

**Recommended tests**
None        

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A301d4953f8384f35a5694f30055c1b0fd9c9c5db&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Comment by iryabov** [comment]
### Drill4J Bot - Change Testing Report

**Changes**
3 methods (1 new, 2 modified)   

**Risks**
2/3 methods not tested
85% coverage

**Recommended tests**
1 test

[See details in Drill4J](http://localhost:8095/dashboard/3?build=realworld%3Aspring-webflux%3A7f92dcb6f24a9967793b11f11b8795bd2a2d93e4&baseline_build=realworld%3Aspring-webflux%3A07927147df0afedcbaf90313ca63e26d750bfa85)

**Pull request closed without merging**
